# Generated by Django 2.2.5 on 2020-09-22 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylifemodel',
            name='time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)], verbose_name='学習時間(単位:時間)'),
        ),
        migrations.AlterField(
            model_name='studylifemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studylifemodel',
            constraint=models.UniqueConstraint(fields=('date', 'task'), name='unique_task'),
        ),
    ]
