# Generated by Django 2.2.5 on 2020-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_auto_20200922_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylifemodel',
            name='task',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
