# Generated by Django 2.2.5 on 2020-09-23 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyapp', '0004_auto_20200923_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='学習内容を登録'),
        ),
    ]
