# Generated by Django 2.2.5 on 2020-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_auto_20200923_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylifemodel',
            name='task',
            field=models.CharField(choices=[('1', 'プログラミング'), ('2', '語学'), ('3', '資格'), ('4', '読書'), ('5', 'その他')], max_length=1, verbose_name='学習内容'),
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
